{% set version = "2.3.3" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: 27c52620bd364d1c8116eaac4ea2afcbfb81ae9139fb3199652fcac1724bfb6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-crc32c >=1.0,<2.0.0dev
  run_constrained:
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev

test:
  requires:
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - johanneskoester
    - leahecole
    - parthea
    - tswast
