{% set version = "2.4.0" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: 8d5518502f92b9ecc84ac46779bd4f09694ecb3ba38a3e7ca737a86d15cbca1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-crc32c >=1.0,<2.0.0dev
  run_constrained:
    - requests >=2.18.0,<3.0.0dev
    - aiohttp >=3.6.2,<4.0.0dev

test:
  requires:
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - johanneskoester
    - leahecole
    - parthea
    - tswast
