{% set version = "0.7.1" %}

package:
  name: google-resumable-media
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-{{ version }}.tar.gz
  sha256: 57841f5e65fb285c01071f439724745b2549a72eb75e5fd979198eb518608ed0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - google-crc32c >=0.1.0,<0.2dev
  run_constrained:
    - requests >=2.18.0,<3.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - google
    - google.resumable_media
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/google-resumable-media-python
  summary: Utilities for Google Media Downloads and Resumable Uploads
  doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
  dev_url: https://github.com/googleapis/google-resumable-media-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - leahecole
    - parthea
    - tswast
